package convex.db.lattice;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

import convex.core.data.ABlob;
import convex.core.data.ACell;
import convex.core.data.AString;
import convex.core.data.AVector;
import convex.core.data.Index;
import convex.core.data.prim.CVMLong;

/**
 * Per-table lazily-seeded monotonic counters generating small, sequential
 * auto-increment primary key values — the counterpart to
 * {@link AutoIncrementRegistry}'s purely declarative marker.
 *
 * <p>Deliberately NOT the {@code Math.max(prev+1, System.currentTimeMillis())}
 * HLC-style pattern used by {@code SQLSchema.WRITE_SEQ}/{@code
 * VersionedSQLTable.nextHistorySeq}/{@code Querylog.nextLogId} — those exist
 * to generate ordering values where the actual number doesn't matter, only
 * relative ordering across a distributed system, and produce huge
 * millis-scale values as a result. An auto-increment PRIMARY KEY is a
 * business-visible value an application may embed in URLs, expect to fit an
 * ordinary column, etc. — callers need small, sequential-looking ids
 * matching what MySQL/PostgreSQL would generate, seeded from whatever data
 * (e.g. migrated historical rows) already exists.
 *
 * <p>Process-local, like the HLC counters above — not persisted to the
 * lattice. A fresh process re-seeds a table's counter from {@code
 * MAX(existing PK)} the first time either {@link #nextValue} or {@link
 * #recordValue} touches that table, which is always correct (reflects the
 * live table's actual current state) rather than relying on remembered
 * state from a previous run. Both methods seed identically on first use —
 * regardless of whether a table's very first touch in this process is a
 * generate or an explicit-value insert, the counter always starts from the
 * table's true current max, not an incomplete view.
 *
 * <p>Safe under the rare cross-node race this system's distributed nature
 * allows (two nodes both generating a value before either replicates to the
 * other): {@link #nextCandidate} only ever hands out a <em>candidate</em> —
 * the caller (see {@code SQLSchema.insert}) must claim it via {@code
 * SQLTable#insertRowIfAbsent}, which atomically checks-and-writes within a
 * single lattice update, and retry with the next candidate if that reports
 * the slot was already taken. Deliberately not validated here via a
 * separate pre-check-then-later-write: a check now paired with a write
 * later would leave the exact same TOCTOU race window {@code
 * insertRowIfAbsent} exists to close (found live 2026-08-11, before this
 * version shipped — a candidate could pass a standalone existence check and
 * then still collide with something written in the gap before the caller's
 * own subsequent write, silently clobbering it).
 */
public class AutoIncrementCounters {

	private static final ConcurrentHashMap<AString, ConcurrentHashMap<AString, AtomicLong>> BY_SCHEMA =
		new ConcurrentHashMap<>();

	private AutoIncrementCounters() {}

	private static ConcurrentHashMap<AString, AtomicLong> tablesFor(AString schemaName) {
		return BY_SCHEMA.computeIfAbsent(schemaName, k -> new ConcurrentHashMap<>());
	}

	/**
	 * Returns the next candidate auto-increment value for {@code
	 * tableName}'s (single-column) primary key, seeding the counter from
	 * the table's own {@code MAX(existing PK)} on first use. A candidate is
	 * NOT guaranteed free — the caller must claim it atomically (see this
	 * class's own doc) and call this again for a fresh candidate if the
	 * claim fails. Never reuses a gap left by a deleted row, matching
	 * MySQL's own auto_increment behaviour.
	 */
	public static long nextCandidate(SQLSchema schema, AString tableName) {
		return counterFor(schema, tableName).incrementAndGet();
	}

	/**
	 * Records that {@code valueUsed} was just written (whether generated by
	 * {@link #nextCandidate} or supplied explicitly by a caller) so the counter
	 * never later generates a value that collides with it — mirrors
	 * MySQL's own behaviour where an explicit INSERT ahead of the current
	 * auto_increment counter pulls the counter forward.
	 */
	public static void recordValue(SQLSchema schema, AString tableName, long valueUsed) {
		AtomicLong counter = counterFor(schema, tableName);
		long prev;
		do {
			prev = counter.get();
			if (prev >= valueUsed) return;
		} while (!counter.compareAndSet(prev, valueUsed));
	}

	/** Clears a table's counter (e.g. on DROP TABLE), so a later re-CREATE of the same name re-seeds from scratch. */
	public static void unmark(AString schemaName, AString tableName) {
		Map<AString, AtomicLong> tables = BY_SCHEMA.get(schemaName);
		if (tables != null) tables.remove(tableName);
	}

	private static AtomicLong counterFor(SQLSchema schema, AString tableName) {
		return tablesFor(schema.getSchemaName()).computeIfAbsent(tableName,
			k -> new AtomicLong(seedFromExistingData(schema, tableName)));
	}

	private static long seedFromExistingData(SQLSchema schema, AString tableName) {
		long max = 0;
		Index<ABlob, AVector<ACell>> all = schema.selectAll(tableName);
		if (all != null) {
			for (Map.Entry<ABlob, AVector<ACell>> e : all.entrySet()) {
				ACell pk = e.getValue().get(0);
				if (pk instanceof CVMLong l) max = Math.max(max, l.longValue());
			}
		}
		return max;
	}
}
